name: Delete obsolete branches from destination.
on:
  delete
env:
  DEST_REPO: michaltc/workspace-microapps-bundles
  DEST_REPO_DIR: ../workspace-microapps-bundles
  BUNDLES_DIR: bundles
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v1

      - name: Checkout destination repository
        uses: actions/checkout@v1
        with:
          repository: ${{ env.DEST_REPO }}
          ref: master

      # GitHub Action unfortunatelly doesn't provide name of the deleted branch in the `delete` event. GITHUB_SHA and
      # GITHUB_REF variables refer to the default branch (master). Diff of branches is used as a dirty workaround.
      - name: Delete obsolete branches
        run: |
          set -x
          git branch --remotes --format='%(refname:short)' | sed 's%^origin/%%' | sort | tee /tmp/branches_source.txt
          cd $DEST_REPO_DIR
          git branch --remotes --format='%(refname:short)' | sed 's%^origin/%%' | sort | tee /tmp/branches_destination.txt

          comm -13 /tmp/branches_source.txt /tmp/branches_destination.txt | tee /tmp/branches_delete.txt

          for branch in $(cat /tmp/branches_delete.txt)
          do
            echo "$branch"
            git push origin --delete "$branch"
          done
