name: Prepare bundles
on:
  push:
#    branches:
#      - '*'
#    paths:
#      - 'bundles/*'
#      - '.github/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build bundles
        uses: ./.github/actions/build-bundles
        with:
          output_path: "./dist"

      # https://github.com/EndBug/add-and-commit
      - name: Commit changes
        uses: EndBug/add-and-commit@v2.1.0
        with:
          message: "Prepare bundles"
          path: "./dist"
          #pattern: "*.*"
          #force: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
