name: Prepare bundles
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Build and execute bundlegen
        run: |
          pushd bundlegen
          mvn clean package exec:java -Dexec.mainClass="com.citrix.microapps.bundlegen.BundlegenMain"
          popd

      # https://github.com/EndBug/add-and-commit
      - name: Commit changes
        uses: EndBug/add-and-commit@v2.1.0
        with:
          message: "Prepare bundles"
          path: "./dist"
          #pattern: "*.*"
          #force: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
